services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:example@db:5432/mydatabase
    depends_on:
      - db
    volumes:
      - ./app:/app

# docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "8765:8765"
    volumes:
      - ./pg_data:/var/lib/postgresql/data